Added helper functions for handling The Siren's Steal attack
IsaacScript/isaacscript-common pull request #6
Opened 2021-11-08 05:30 UTC by KyojoH

2021-11-08 05:52 UTC, Zamiell commented on src/features/sirenHelpers.ts
> + *
bug

2021-11-08 05:52 UTC, Zamiell commented on src/features/sirenHelpers.ts
> +export function isStolen(familiar: EntityFamiliar): boolean {
how about hasSirenStolen

2021-11-08 05:53 UTC, Zamiell commented on src/features/sirenHelpers.ts
> +export function init(incomingMod: Mod): void {
put init at the top under the v declaration

2021-11-08 05:53 UTC, Zamiell commented on src/features/sirenHelpers.ts
> + * @returns Returns the hidden 'Siren Helper' entity corresponding to the given familiar, if it
use complete sentances

2021-11-08 05:54 UTC, Zamiell commented on src/features/sirenHelpers.ts
> + * @param familiarVariant The familiar variant to blacklist
same here

2021-11-08 21:25 UTC, KyojoH commented on src/features/sirenHelpers.ts
> + *
what's the bug? i don't see one

2021-11-08 21:27 UTC, KyojoH commented on src/features/sirenHelpers.ts
> +const sirenHelperData: {
it's an int, although [int,int][] gets fixed by eslint or prettier to Array<[int,int]>

2021-11-08 21:36 UTC, KyojoH commented on src/features/sirenHelpers.ts
> + * This function checks whether the Siren has stolen a familiar.
yes

2021-11-08 21:44 UTC, Zamiell requested changes

2021-11-08 21:44 UTC, Zamiell commented on src/features/sirenHelpers.ts
> +export function hasSirenStolen(familiar: EntityFamiliar): boolean {
hasSirenStolenFamiliar

2021-11-08 21:44 UTC, Zamiell commented on src/features/sirenHelpers.ts
> +function blacklistEntryExists(newBlacklistEntry: [number, number]) {
use a named tuple + object destructuring. this is a no magic zone

2021-11-08 21:44 UTC, Zamiell commented on src/features/sirenHelpers.ts
> +const sirenHelperData = {
use the const v convention. v is short for local variables and is the same in every file

2021-11-09 06:06 UTC, KyojoH commented on src/features/sirenHelpers.ts
> +const sirenHelperData = {
done

2021-11-09 06:06 UTC, KyojoH commented on src/features/sirenHelpers.ts
> +function blacklistEntryExists(newBlacklistEntry: [number, number]) {
done

2021-11-09 06:06 UTC, KyojoH commented on src/features/sirenHelpers.ts
> +export function hasSirenStolen(familiar: EntityFamiliar): boolean {
done

2021-11-09 06:06 UTC, KyojoH commented on src/features/sirenHelpers.ts
> +export function getSirenHelper(familiar: EntityFamiliar): Entity | undefined {
done

2021-11-09 06:06 UTC, KyojoH commented on src/features/sirenHelpers.ts
> +let mod: Mod | null = null;
done

2021-11-09 06:06 UTC, KyojoH commented on src/features/sirenHelpers.ts
> +export function forceNoSiren(
changed

2021-11-09 14:54 UTC, merged